news-app/main/default/objects/ToDoList__c/ToDoList__c.object-meta.xml
<CustomObject>
    <description>Holds to do list items for the user</description>
    <label>ToDoList</label>
    <nameField>
        <displayFormat>TODO-{000000}</displayFormat>
        <label>ToDoList Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ToDoList</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

news-app/main/default/objects/ToDoList__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if completed</description>
    <label>Completed</label>
    <type>Checkbox</type>
</CustomField>

news-app/main/default/objects/ToDoList__c/fields/ToDo_Item__c.field-meta.xml
<CustomField>
    <fullName>ToDo_Item__c</fullName>
    <description>A single to do item</description>
    <label>ToDo_Item</label>
    <type>TextArea</type>
</CustomField>

news-app/main/default/classes/ToDoController.cls
public with sharing class ToDoController {
    
    @AuraEnabled
    public static void addToDoItem(String todoItem, Boolean completed) {
        ToDoList__c todo = new ToDoList__c(ToDo_Item__c=todoItem, Completed__c=completed);
        insert todo;
    }

    @AuraEnabled
    public static void updateToDoItem(ID todoid, Boolean completed){
        ToDoList__c todo = new ToDoList__c(ID=todoid, Completed__c=completed);
        upsert todo;
    }

    @AuraEnabled
    public static List<ToDoList__c> getToDoItems() {
        return [ SELECT ToDo_Item__c,Completed__c FROM ToDoList__c WHERE OwnerId=:UserInfo.getUserId() ORDER BY createdDate ];
    }

    @AuraEnabled
    public static void deleteTodoItem(String todoID){
        ToDoList__c todo = [ SELECT ID FROM ToDoList__c WHERE ID=:todoID ];
        delete todo;
    }
}